### ISSUE TITLE
Python if statement grabs full text

### ISSUE THREAD

**Issue by schererja** [code-biscuits/assorted-biscuits#1]
When doing an if else statement, Annotation takes full statement
![image](https://user-images.githubusercontent.com/8645717/97747591-36c43680-1aba-11eb-898f-6dc884a270f9.png)

Simple example:
```
status_code = 200
if status_code == 200:
    print("Hello world")
else:
    print("Goodbye World")
```

Windows 10
Python 3.8.1
VSCode 1.50.1

**Comment by cmgriffing** [comment]
Thats working as expected. We show the full string so that we get the extra context.

If you would like a shorter string, you can set a max length in settings. `assorted-biscuits.annotationMaxLength`
