### ISSUE TITLE
how to disable a specific language ?

### ISSUE THREAD

**Issue by ctf0** [code-biscuits/assorted-biscuits#8]
ex.`json`

**Comment by cmgriffing** [comment]
Hmm, good call. I should have some kind of enabled/disabled checkbox in the config.

As a temporary workaround, you could set the "Distance" for that language to a very high value like 99999.

**Comment by ctf0** [comment]
> As a temporary workaround, you could set the "Distance" for that language to a very high value like 99999.

it wont work, because the file still being parsed + adding very big margin means the renderer still calculates it b4 giving up.

**Comment by cmgriffing** [comment]
Oh right. Ok I will work on this over the weekend.
